
version: '3.3'
services:
  product-search-challenge:
    container_name: 'product-search-challenge'
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${HTTP_IN_PORT}:${HTTP_IN_PORT}'


  
